version: "3.8"
services:
  backend-pokemon-app:
    build:
      context: ./backend-pokemon-app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend-pokemon-app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend-pokemon-app:
    build:
      context: ./frontend-pokemon-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend-pokemon-app:/app
