version: "3"
services:
  db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 12345
    networks:
      - my-network

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my-network

networks:
  my-network:
